Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  Exclude:
    - 'bin/setup'
    - 'bin/update'
    - 'config/deploy.rb'
    - 'config/deploy/production.rb'
