production:
  adapter: mysql2
  encoding: utf8
  database: patreewi_tesse59
  username: patreewi_tesse59
  password: LrJNoBddBq
  host: mysql5.locum.ru

development:
  adapter: mysql2
  encoding: utf8
  database: patreewi_tesse59
  username: patreewi_tesse59
  password: LrJNoBddBq
  host: mysql5.locum.ru
